### PR TITLE
add timestep to prediction methods in system models

### PR DESCRIPTION
**Pull request by jwdinius**
It would be useful to account for timestep in the prediction methods.  I added logic to extend the system models to optionally use the timestep in the prediction methods.

### CODE REVIEW

**Comment by yaxn** [comment]
I think this is a bad idea, because the Kalman filter works with count, and time in seconds is used in transition matrix F of custom SystemModel class.

**Comment by jwdinius** [comment]
@yaxn I don't believe I understand your comment.  What do you mean "the Kalman filter works with count"?  The KalmanFilter classes have no member that keeps track of count/iterations.  I am trying to add the ability to account for timestep in the prediction step.  It may be desirable to have this ability because of the fact that there may be irregular time between measurement updates.  All existing logic will function as it did previously, I am just adding the _option_ to include the timestep.  It isn't required.

**Comment by jwdinius** [comment]
I'm closing because I would like to consider other options for handling non autonomous (e.g. time dependent) systems.

**Comment by JinglinZhang** [comment]
> I'm closing because I would like to consider other options for handling non autonomous (e.g. time dependent) systems.

I think the timestamp could be a member of control vector if needed.

**Pull request closed without merging**
